### PR TITLE
Requiring file_upload

### PR DESCRIPTION
**Pull request by marcofognog**
I needed to change this in order to make it work for me. Working good so far, thanks for this lib.

### CODE REVIEW

**Comment by camelpunch** [comment]
Hi there. I can't pull the policy changes without specs. Why did you need to change the policy code?

**Comment by marcofognog** [comment]
Oh, sorry, my bad. I pulled the request, forgot it and changed the code, please ignore this pull.

**Comment by camelpunch** [comment]
Interested to know how it didn't work for you. I also want to refactor FileUpload since it's exposing too much of its internals.

What was going wrong?

**Comment by marcofognog** [comment]
All answer you in another thread.

**Pull request closed without merging**
